// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLkgaVZwWubUksqrki-tnXkTZMO6f1Od8',
    appId: '1:572790136411:web:7dc398ecaee892e19d297e',
    messagingSenderId: '572790136411',
    projectId: 'plantwateringapp-7efbf',
    authDomain: 'plantwateringapp-7efbf.firebaseapp.com',
    storageBucket: 'plantwateringapp-7efbf.firebasestorage.app',
    measurementId: 'G-1HNSPNEQ0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKJtPyzI9JEkPqCP_ziuaTO4htzIc7d-8',
    appId: '1:572790136411:android:50a0a0cbaaf6528b9d297e',
    messagingSenderId: '572790136411',
    projectId: 'plantwateringapp-7efbf',
    storageBucket: 'plantwateringapp-7efbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz7rMbl6rxlqNVazRxh8LD_6F5JwGrAIg',
    appId: '1:572790136411:ios:cc2a2fbcbea4d6be9d297e',
    messagingSenderId: '572790136411',
    projectId: 'plantwateringapp-7efbf',
    storageBucket: 'plantwateringapp-7efbf.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz7rMbl6rxlqNVazRxh8LD_6F5JwGrAIg',
    appId: '1:572790136411:ios:cc2a2fbcbea4d6be9d297e',
    messagingSenderId: '572790136411',
    projectId: 'plantwateringapp-7efbf',
    storageBucket: 'plantwateringapp-7efbf.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLkgaVZwWubUksqrki-tnXkTZMO6f1Od8',
    appId: '1:572790136411:web:dfe106bc4cc343059d297e',
    messagingSenderId: '572790136411',
    projectId: 'plantwateringapp-7efbf',
    authDomain: 'plantwateringapp-7efbf.firebaseapp.com',
    storageBucket: 'plantwateringapp-7efbf.firebasestorage.app',
    measurementId: 'G-1B90Q6T7G8',
  );
}
